### PR TITLE
MCP-1155 PDF Generator

### PR DESCRIPTION
**Pull request by anthonyvelazquez**
Install the following pip packages to be able to run the script:

- `pip install pdfkit jinja2`

How to run:

1. Navigate to `pdf_generator/pdf_generator.py` and modify the values in `template_variables`
2. Run the following: `python pdf_generator/pdf_generator.py`

This script will look inside the `pdf_generator/templates` folder for a `hypertension.html` file and will use it to generate a new HTML file with all the appropriate data and output that to `pdf_generator/generated_files`. Lastly, PDFKit will take that generated file and turn it into a PDF and save the file in `pdf_generator/output`

### CODE REVIEW

**Review by jbregstone — COMMENTED** [review]
Do these changes mean we are no longer reliant on wkhtmltopdf ? Also if we add a new dependency it mean we have to decide if we are keeping Poetry as a package manager. The AWS config just uses a requirements.txt I think it would be simpler to do the same.

**Comment by anthonyvelazquez** [comment]
> Do these changes mean we are no longer reliant on wkhtmltopdf ? Also if we add a new dependency it mean we have to decide if we are keeping Poetry as a package manager. The AWS config just uses a requirements.txt I think it would be simpler to do the same.

So [PDFKit](https://github.com/JazzCore/python-pdfkit) is a Python wrapper for wkhtmltopdf. We should still be able to just use the lambda layer for wkhtmltopdf and add the pip package in the requirements.txt or worst case have 2 layers, 1 for the binary and 1 for the pip packages

**Comment by jbregstone** [comment]
> 

OK gotcha, ya that makes sense. For the purposes of this PR I think we should try to add PDFKIT as a dependency to Poetry lock file. It will look something like this

`poetry add pdfkit jinja2`

https://python-poetry.org/docs/cli/#add

**Comment by jbregstone** [comment]
Take a look at `hypertension/py-root/lib/main.py` and `hypertension/py-root/lib/pdf_generator.py` to see if we can replace the current pdf output with the new one you created!

**Comment by anthonyvelazquez** [comment]
Merging this. Will add service updates to https://github.com/amida-tech/Virtual-Regional-Office/pull/6

**Pull request merged**
